# Generated by Django 4.0.3 on 2022-03-23 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question_app', '0002_profile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, null=True)),
                ('choice1', models.CharField(max_length=150, null=True)),
                ('choice2', models.CharField(max_length=150, null=True)),
                ('choice3', models.CharField(max_length=150, null=True)),
                ('choice4', models.CharField(max_length=150, null=True)),
                ('answer', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
